---
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    namespace: dolittle-campaigns
    name: signup
  spec:
    replicas: 1
    selector:
      matchLabels:
        campaign: signup
    template:
      metadata:
        labels:
          campaign: signup
      spec:
        containers:
        - name: signup
          image: dolittle/signup
          imagePullPolicy: Always
          ports:
          - containerPort: 80

---
  apiVersion: v1
  kind: Service
  metadata:
    namespace: dolittle-campaigns
    name: signup
  spec:
    type: LoadBalancer
    ports:
    - port: 80
      name: http
      protocol: TCP
    selector:
      campaign: signup

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  namespace: dolittle-campaigns
  name: signup
spec:
  rules:
  - host: signup.dolittle.com
    http:
      paths:
      - path: /
        backend:
          serviceName: signup
          servicePort: 80
