---
  kind: Deployment
  apiVersion: extensions/v1beta1
  metadata:
    name: signup
    namespace: dolittle
  spec:
    template:
      metadata:
        labels:
          app: signup
          name: signup
      spec:
        containers:
        - name: signup
          image: dolittle/signup
          imagePullPolicy: Always
          ports:
          - containerPort: 80
---
  apiVersion: v1
  kind: Service
  metadata:
    name: signup
    namespace: dolittle
    labels:
      app: signup
  spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      name: signup-port
      protocol: TCP
    selector:
      app: signup
      name: signup
  